spring:
  application:
    name: doramadreams

  datasource:
    url: jdbc:postgresql://localhost:5432/dorama_dreams_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    
tmdb:
  api-key: ca1df7f89eebfe030f2f574f3b814ef8

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: doramas
  public-url: http://localhost:9000

server:
  port: 8080