spring:
  application:
    name: doramadreams

  datasource:
    url: jdbc:postgresql://localhost:5432/dorama_dreams_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html

server:
  port: 8080